// Generated by generate-costing-options.py from Valhalla's OpenAPI spec (openapi.yaml), do not edit.
const COSTING_OPTIONS = {
  types: [
    "auto",
    "bicycle",
    "pedestrian",
    "truck",
    "bus",
    "taxi",
    "motor_scooter",
    "motorcycle",
    "multimodal",
    "bikeshare",
    "auto_pedestrian",
  ],
  costings: {
    auto: "Auto",
    bus: "Auto",
    taxi: "Auto",
    bicycle: "Bicycle",
    pedestrian: "Pedestrian",
    bikeshare: "Pedestrian",
    truck: "Truck",
    motorcycle: "Motorcycle",
    motor_scooter: "MotorScooter",
    multimodal: "Transit",
    transit: "Transit",
  },
  schemas: {
    Base: [
      {
        name: "exclude_bridges",
        type: "boolean",
        default: false,
        description:
          "This value indicates whether or not the path may include bridges. If `exclude_bridges` is set to true it is allowed to start and end with bridges, but is not allowed to have them in the middle of the route path, otherwise they are allowed. If set to true, it is highly plausible that no path will be found.",
      },
      {
        name: "exclude_tunnels",
        type: "boolean",
        default: false,
        description:
          "This value indicates whether or not the path may include tunnels. If `exclude_tunnels` is set to true it is allowed to start and end with tunnels, but is not allowed to have them in the middle of the route path, otherwise they are allowed. If set to true, it is highly plausible that no path will be found.",
      },
      {
        name: "exclude_tolls",
        type: "boolean",
        default: false,
        description:
          "This value indicates whether or not the path may include tolls. If `exclude_tolls` is set to true it is allowed to start and end with tolls, but is not allowed to have them in the middle of the route path, otherwise they are allowed. If set to true, it is highly plausible that no path will be found.",
      },
      {
        name: "exclude_highways",
        type: "boolean",
        default: false,
        description:
          "This value indicates whether or not the path may include highways. If `exclude_highways` is set to true it is allowed to start and end with highways, but is not allowed to have them in the middle of the route path, otherwise they are allowed. If set to true, it is highly plausible that no path will be found.",
      },
      {
        name: "exclude_ferries",
        type: "boolean",
        default: false,
        description:
          "This value indicates whether or not the path may include ferries. If `exclude_ferries` is set to true it is allowed to start and end with ferries, but is not allowed to have them in the middle of the route path, otherwise they are allowed. If set to true, it is highly plausible that no path will be found.",
      },
      {
        name: "shortest",
        type: "boolean",
        default: false,
        description:
          "Changes the metric to quasi-shortest, i.e. purely distance-based costing. Note, this will disable all other costings & penalties. Also note, `shortest` will not disable hierarchy pruning, leading to potentially sub-optimal routes for some costing models.",
      },
      {
        name: "disable_hierarchy_pruning",
        type: "boolean",
        default: false,
        description:
          "Disable graph hierarchy culling; if the bee-line distance between waypoints exceeds the config parameter value for service_limits.max_distance_disable_hierarchy_culling, the option is ignored",
      },
      {
        name: "ignore_restrictions",
        type: "boolean",
        description:
          "If set to `true`, ignores any restrictions (e.g. turn/dimensional/conditional restrictions). Especially useful for matching GPS traces to the road network regardless of restrictions.",
      },
      {
        name: "ignore_oneways",
        type: "boolean",
        default: false,
        description:
          "If set to `true`, ignores one-way restrictions. Especially useful for matching GPS traces to the road network ignoring uni-directional traffic rules. Not included in `ignore_restrictions` option.",
      },
      {
        name: "ignore_access",
        type: "boolean",
        default: false,
        description:
          "Will ignore mode-specific access tags. Especially useful for matching GPS traces to the road network regardless of restrictions",
      },
      {
        name: "ignore_closures",
        type: "boolean",
        default: false,
        description:
          "If set to `true`, ignores all closures, marked due to live traffic closures, during routing. **Note:** This option cannot be set if `location.search_filter.exclude_closures` is also specified in the request and will return an error if it is.",
      },
      {
        name: "destination_only_penalty",
        type: "number",
        default: 600,
        minimum: 0,
        maximum: 43200,
        description:
          "A penalty applied when entering an road which is only allowed to enter if necessary to reach the [destination](https://wiki.openstreetmap.org/wiki/Tag:vehicle%3Ddestination).",
      },
      {
        name: "maneuver_penalty",
        type: "number",
        default: 5,
        minimum: 0,
        maximum: 43200,
        description:
          "A penalty applied when transitioning between roads that do not have consistent naming — in other words, no road names in common. This penalty can be used to create simpler routes that tend to have fewer maneuvers or narrative guidance instructions. The default maneuver penalty is five seconds.",
      },
      {
        name: "alley_penalty",
        type: "number",
        minimum: 0,
        maximum: 43200,
        description:
          "A penalty that is applied when transitioning onto an alley. Default is 60 seconds for bicycle, 5 seconds otherwise.",
      },
      {
        name: "gate_cost",
        type: "number",
        default: 30,
        minimum: 0,
        maximum: 43200,
        description:
          "A cost applied when a [gate](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dgate) with undefined or private access is encountered. This cost is added to estimated and elapsed times.",
      },
      {
        name: "gate_penalty",
        type: "number",
        minimum: 0,
        maximum: 43200,
        description:
          "A penalty applied when a [gate](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dgate) with no access information is on the road. Default is 300 for bicycle, 30 otherwise.",
      },
      {
        name: "private_access_penalty",
        type: "number",
        minimum: 0,
        maximum: 43200,
        description:
          "A penalty applied when a [gate](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dgate) or [bollard](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dbollard) with `access=private` is encountered. Default is 600 for pedestrian, 450 otherwise.",
      },
      {
        name: "country_crossing_cost",
        type: "number",
        default: 600,
        minimum: 0,
        maximum: 43200,
        description:
          "A cost applied when encountering an international border. This cost is added to the estimated and elapsed times.",
      },
      {
        name: "country_crossing_penalty",
        type: "number",
        default: 0,
        minimum: 0,
        maximum: 43200,
        description:
          "A penalty applied for a country crossing. This penalty can be used to create paths that avoid spanning country boundaries.",
      },
      {
        name: "ferry_cost",
        type: "number",
        default: 300,
        minimum: 0,
        maximum: 43200,
        description:
          "A cost applied when entering a ferry. This cost is added to the estimated and elapsed times.",
      },
      {
        name: "use_ferry",
        type: "number",
        default: 0.5,
        minimum: 0,
        maximum: 1,
        description:
          "This value indicates the willingness to take ferries. This is a range of values between 0 and 1. Values near 0 attempt to avoid ferries and values near 1 will favor ferries. Note that sometimes ferries are required to complete a route so values of 0 are not guaranteed to avoid ferries entirely.",
      },
      {
        name: "rail_ferry_cost",
        type: "number",
        default: 300,
        minimum: 0,
        maximum: 43200,
        description:
          "A cost applied when entering a rail ferry. This cost is added to the estimated and elapsed times.",
      },
      {
        name: "use_rail_ferry",
        type: "number",
        default: 0.4,
        minimum: 0,
        maximum: 1,
        description:
          "This value indicates the willingness to take rail ferries. This is a range of values between 0 and 1. Values near 0 attempt to avoid rail ferries and values near 1 will favor them. Note that sometimes rail ferries may be required to complete a route so values of 0 are not guaranteed to avoid them entirely.",
      },
      {
        name: "toll_booth_cost",
        type: "number",
        default: 15,
        minimum: 0,
        maximum: 43200,
        description:
          "A cost applied when a [toll booth](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dtoll_booth) is encountered. This cost is added to the estimated and elapsed times.",
      },
      {
        name: "toll_booth_penalty",
        type: "number",
        default: 0,
        minimum: 0,
        maximum: 43200,
        description:
          "A penalty applied to the cost when a [toll booth](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dtoll_booth) is encountered. This penalty can be used to create paths that avoid toll roads.",
      },
      {
        name: "service_penalty",
        type: "number",
        minimum: 0,
        maximum: 43200,
        description:
          "A penalty applied for transition to generic service road. The default penalty is 0 for trucks and pedestrian, 75 for auto/bus/taxi, 15 otherwise.",
      },
      {
        name: "service_factor",
        type: "number",
        default: 1.0,
        minimum: 0.1,
        maximum: 100000,
        description:
          "A factor that modifies (multiplies) the cost when generic service roads are encountered.",
      },
      {
        name: "use_tracks",
        type: "number",
        minimum: 0,
        maximum: 1,
        description:
          "This value indicates the willingness to take track roads. This is a range of values between 0 and 1. Values near 0 attempt to avoid tracks and values near 1 will favor tracks a little bit. The default value is 0 for auto and truck, 0.5 otherwise. Note that sometimes tracks are required to complete a route so values of 0 are not guaranteed to avoid tracks entirely.",
      },
      {
        name: "use_living_streets",
        type: "number",
        minimum: 0,
        maximum: 1,
        description:
          "This value indicates the willingness to take living streets. This is a range of values between 0 and 1. Values near 0 attempt to avoid living streets and values near 1 will favor living streets. The default value is 0 for truck, 0.5 for bicycle, 0.6 for pedestrian, 0.1 otherwise. Note that sometimes living streets are required to complete a route so values of 0 are not guaranteed to avoid living streets entirely.",
      },
      {
        name: "closure_factor",
        type: "number",
        default: 9.0,
        minimum: 1,
        maximum: 10,
        description:
          "A factor that penalizes the cost when traversing a closed edge (eg: if `search_filter.exclude_closures` is `false` for origin and/or destination location and the route starts/ends on closed edges). Its value can range from `1.0` - don't penalize closed edges, to `10.0` - apply high cost penalty to closed edges. Default value is `9.0`. **Note:** This factor is applicable only for motorized modes of transport, i.e auto, motorcycle, motor_scooter, bus, truck & taxi.",
      },
      {
        name: "speed_penalty_factor",
        type: "number",
        default: 0.05,
        minimum: 0,
        maximum: 1,
        description:
          "Penalty factor applied for edges when edge speed is faster than top speed. The default value is 0.05. If you want to use `top_speed` without penalizing roads where the edge speed is much lower than `top_speed`, set this value to 0.",
      },
      {
        name: "fixed_speed",
        type: "integer",
        default: 0,
        minimum: 0,
        maximum: 252,
        description:
          "Fixed speed the vehicle can go in km/h. Used to override the calculated speed. Can be useful if speed of vehicle is known. Value must be between 1 and 252. The default value is 0, which disables fixed speed and falls back to the standard calculated speed based on the road attribution.",
      },
    ],
    Auto: [
      {
        name: "alley_factor",
        type: "number",
        default: 1.0,
        minimum: 0.1,
        maximum: 100000,
        description:
          "A factor that modifies (multiplies) the cost when [alleys](https://wiki.openstreetmap.org/wiki/Tag:service%3Dalley) are encountered. Auto routes generally want to avoid alleys or narrow service roads between buildings.",
      },
      {
        name: "use_highways",
        type: "number",
        default: 0.5,
        minimum: 0,
        maximum: 1,
        description:
          "This value indicates the willingness to take highways. This is a range of values between 0 and 1. Values near 0 attempt to avoid highways and values near 1 will favor highways. Note that sometimes highways are required to complete a route so values of 0 are not guaranteed to avoid highways entirely.",
      },
      {
        name: "use_tolls",
        type: "number",
        default: 0.5,
        minimum: 0,
        maximum: 1,
        description:
          "This value indicates the willingness to take roads with tolls. This is a range of values between 0 and 1. Values smaller than 0.5 attempt to avoid tolls and values greater than 0.5 will slightly favor them. A value of 0.5 indicates no preference. Note that sometimes roads with tolls are required to complete a route so values of 0 are not guaranteed to avoid them entirely.",
      },
      {
        name: "use_distance",
        type: "number",
        default: 0,
        minimum: 0,
        maximum: 1,
        description:
          "A factor that allows controlling the contribution of distance and time to the route costs. The value is in range between 0 and 1, where 0 only takes time into account and 1 only distance. A factor of 0.5 will weigh them roughly equally.",
      },
      {
        name: "restriction_probability",
        type: "integer",
        default: 100,
        minimum: 0,
        maximum: 100,
        description:
          "Percentage chance to honour probabilistic access restrictions.",
      },
      {
        name: "top_speed",
        type: "integer",
        default: 140,
        minimum: 10,
        maximum: 252,
        description:
          "Top speed the vehicle can go in km/h. Also used to avoid roads with higher speeds than this value (see speed_penalty_factor for more details). `top_speed` must be between 10 and 252 km/h. The default value is 140 km/h for auto, taxi and bus.",
      },
      {
        name: "include_hov2",
        type: "boolean",
        default: false,
        description:
          "A boolean value which indicates the desire to include HOV roads with a 2-occupant requirement in the route when advantageous.",
      },
      {
        name: "include_hov3",
        type: "boolean",
        default: false,
        description:
          "A boolean value which indicates the desire to include HOV roads with a 3-occupant requirement in the route when advantageous.",
      },
      {
        name: "include_hot",
        type: "boolean",
        default: false,
        description:
          "A boolean value which indicates the desire to include tolled HOV roads which require the driver to pay a toll if the occupant requirement isn't met.",
      },
      {
        name: "height",
        type: "number",
        default: 1.6,
        description:
          "Vehicle height in meters for access restriction matching.",
      },
      {
        name: "width",
        type: "number",
        default: 1.9,
        description: "Vehicle width in meters for access restriction matching.",
      },
      {
        name: "length",
        type: "number",
        default: 2.7,
        description:
          "Vehicle length in meters for access restriction matching.",
      },
      {
        name: "weight",
        type: "number",
        default: 0.8,
        description:
          "Vehicle weight in metric tons for access restriction matching.",
      },
    ],
    Bicycle: [
      {
        name: "bicycle_type",
        type: "string",
        default: "hybrid",
        enum: ["road", "hybrid", "city", "cross", "mountain"],
        description:
          "The type of bicycle. Affects the cycling speed and surface factors.",
      },
      {
        name: "cycling_speed",
        type: "number",
        minimum: 5,
        description:
          "Cycling speed in km/h. Defaults depend on transport_type.",
      },
      {
        name: "use_roads",
        type: "number",
        default: 0.25,
        minimum: 0,
        maximum: 1,
        description:
          "A cyclist's propensity to use roads alongside other vehicles. This is a range of values from 0 to 1, where 0 attempts to avoid roads and stay on cycleways and paths, and 1 indicates the rider is more comfortable riding on roads. Based on the `use_roads` factor, roads with certain classifications and higher speeds are penalized in an attempt to avoid them when finding the best path.",
      },
      {
        name: "use_hills",
        type: "number",
        default: 0.25,
        minimum: 0,
        maximum: 1,
        description:
          "A cyclist's desire to tackle hills in their routes. This is a range of values from 0 to 1, where 0 attempts to avoid hills and steep grades even if it means a longer (time and distance) path, while 1 indicates the rider does not fear hills and steeper grades. Based on the `use_hills` factor, penalties are applied to roads based on elevation change and grade. These penalties help the path avoid hilly roads in favor of flatter roads or less steep grades where available. Note that it is not always possible to find alternate paths to avoid hills (for example when route locations are in mountainous areas).",
      },
      {
        name: "avoid_bad_surfaces",
        type: "number",
        default: 0.25,
        minimum: 0,
        maximum: 1,
        description:
          "This value is meant to represent how much a cyclist wants to avoid roads with poor surfaces relative to the bicycle type being used. This is a range of values between 0 and 1. When the value is 0, there is no penalization of roads with different surface types; only bicycle speed on each surface is taken into account. As the value approaches 1, roads with poor surfaces for the bike are penalized heavier so that they are only taken if they significantly improve travel time. When the value is equal to 1, all bad surfaces are completely disallowed from routing, including start and end points.",
      },
      {
        name: "bss_return_cost",
        type: "number",
        default: 120,
        minimum: 0,
        maximum: 43200,
        description:
          "This value is useful when `bikeshare` is chosen as travel mode. It is meant to give the time will be used to return a rental bike. This value will be displayed in the final directions and used to calculate the whole duration.",
      },
      {
        name: "bss_rent_penalty",
        type: "number",
        default: 0,
        minimum: 0,
        maximum: 43200,
        description:
          "This value is useful when `bikeshare` is chosen as travel mode. It is meant to describe the potential effort to return a rental bike. This value won't be displayed and used only inside of the algorithm.",
      },
    ],
    MotorScooter: [
      {
        name: "top_speed",
        type: "integer",
        default: 45,
        minimum: 20,
        maximum: 252,
        description:
          "Top speed the vehicle can go in km/h. Also used to avoid roads with higher speeds than this value. `top_speed` must be between 10 and 252 km/h. The default value is 45 km/h for motor_scooter.",
      },
      {
        name: "use_hills",
        type: "number",
        default: 0.5,
        minimum: 0,
        maximum: 1,
        description:
          "A rider's desire to use hills in their routes. This is a range of values from 0 to 1, where 0 attempts to avoid hills and steep grades even if it means a longer (time and distance) path, while 1 indicates the rider does not fear hills and steeper grades. Based on the `use_hills` factor, penalties are applied to roads based on elevation change and grade. These penalties help the path avoid hilly roads in favor of flatter roads or less steep grades where available. Note that it is not always possible to find alternate paths to avoid hills (for example when route locations are in mountainous areas).",
      },
      {
        name: "use_primary",
        type: "number",
        default: 0.5,
        minimum: 0,
        maximum: 1,
        description:
          "A rider's propensity to use primary roads. This is a range of values from 0 to 1, where 0 attempts to avoid primary roads, and 1 indicates the rider is more comfortable riding on primary roads. Based on the `use_primary` factor, roads with certain classifications and higher speeds are penalized in an attempt to avoid them when finding the best path.",
      },
      {
        name: "use_distance",
        type: "number",
        default: 0,
        minimum: 0,
        maximum: 1,
        description:
          "A factor that allows controlling the contribution of distance and time to the route costs. The value is in range between 0 and 1, where 0 only takes time into account and 1 only distance. A factor of 0.5 will weigh them roughly equally.",
      },
    ],
    Motorcycle: [
      {
        name: "use_highways",
        type: "number",
        default: 0.5,
        minimum: 0,
        maximum: 1,
        description:
          "This value indicates the willingness to take highways. This is a range of values between 0 and 1. Values near 0 attempt to avoid highways and values near 1 will favor highways. Note that sometimes highways are required to complete a route so values of 0 are not guaranteed to avoid highways entirely.",
      },
      {
        name: "use_tolls",
        type: "number",
        default: 0.5,
        minimum: 0,
        maximum: 1,
        description:
          "This value indicates the willingness to take roads with tolls. This is a range of values between 0 and 1. Values smaller than 0.5 attempt to avoid tolls and values greater than 0.5 will slightly favor them. The default value is 0.5, indicating no preference. Note that sometimes roads with tolls are required to complete a route so values of 0 are not guaranteed to avoid them entirely.",
      },
      {
        name: "use_trails",
        type: "number",
        default: 0,
        minimum: 0,
        maximum: 1,
        description:
          "A riders's desire for adventure in their routes. This is a range of values from 0 to 1, where 0 will avoid trails, tracks, unclassified or bad surfaces and values towards 1 will tend to avoid major roads and route on secondary roads.",
      },
      {
        name: "top_speed",
        type: "integer",
        default: 140,
        minimum: 10,
        maximum: 252,
        description:
          "Top speed the vehicle can go in km/h. Also used to avoid roads with higher speeds than this value. `top_speed` must be between 10 and 252 km/h. The default value is 140 km/h for motorcycle.",
      },
      {
        name: "use_distance",
        type: "number",
        default: 0,
        minimum: 0,
        maximum: 1,
        description:
          "A factor that allows controlling the contribution of distance and time to the route costs. The value is in range between 0 and 1, where 0 only takes time into account and 1 only distance. A factor of 0.5 will weigh them roughly equally.",
      },
    ],
    Pedestrian: [
      {
        name: "type",
        type: "string",
        default: "foot",
        enum: ["foot", "blind", "wheelchair"],
        description:
          "These options are mutually exclusive. To combine them, use `blind` and pass the options adjusted for `wheelchair` users manually.",
      },
      {
        name: "walking_speed",
        type: "number",
        default: 5.1,
        minimum: 0.5,
        maximum: 25,
        description:
          "Walking speed in km/h. Note that for transport type wheelchair, the default is set to 4.",
      },
      {
        name: "walkway_factor",
        type: "number",
        default: 1.0,
        minimum: 0.1,
        maximum: 100000,
        description:
          "A factor that modifies the cost when encountering roads classified as `footway` (no motorized vehicles allowed), which may be designated footpaths or designated sidewalks along residential roads. Pedestrian routes generally attempt to favor using these [walkways and sidewalks](https://wiki.openstreetmap.org/wiki/Sidewalks).",
      },
      {
        name: "sidewalk_factor",
        type: "number",
        default: 1.0,
        minimum: 0.1,
        maximum: 100000,
        description:
          "A factor that modifies the cost when encountering roads with dedicated sidewalks. Pedestrian routes generally attempt to favor using [sidewalks](https://wiki.openstreetmap.org/wiki/Key:sidewalk).",
      },
      {
        name: "alley_factor",
        type: "number",
        default: 2.0,
        minimum: 0.1,
        maximum: 100000,
        description:
          "A factor that modifies (multiplies) the cost when [alleys](https://wiki.openstreetmap.org/wiki/Tag:service%3Dalley) are encountered. Pedestrian routes generally want to avoid alleys or narrow service roads between buildings.",
      },
      {
        name: "use_lit",
        type: "number",
        default: 0,
        minimum: 0,
        maximum: 1,
        description:
          "This value is a range of values from 0 to 1, where 0 indicates indifference towards lit streets, and 1 indicates that unlit streets should be avoided. Note that even with values near 1, there is no guarantee the returned route will include lit segments.",
      },
      {
        name: "driveway_factor",
        type: "number",
        default: 5.0,
        minimum: 0.1,
        maximum: 100000,
        description:
          "A factor that modifies (multiplies) the cost when encountering a [driveway](https://wiki.openstreetmap.org/wiki/Tag:service%3Ddriveway), which is often a private, service road. Pedestrian routes generally want to avoid driveways (private).",
      },
      {
        name: "step_penalty",
        type: "number",
        minimum: 0,
        maximum: 43200,
        description:
          "A penalty in seconds added to each transition onto a path with [steps or stairs](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dsteps). Higher values apply larger cost penalties to avoid paths that contain flights of steps. The default depends on the `type` parameter (600 for wheelchair, 30 otherwise).",
      },
      {
        name: "max_hiking_difficulty",
        type: "integer",
        default: 1,
        minimum: 0,
        maximum: 6,
        description:
          "This value indicates the maximum difficulty of hiking trails that is allowed. Values between 0 and 6 are allowed. The values correspond to *sac_scale* values within OpenStreetMap, see reference [here](https://wiki.openstreetmap.org/wiki/Key:sac_scale). The default value is 1 which means that well cleared trails that are mostly flat or slightly sloped are allowed. Higher difficulty trails can be allowed by specifying a higher value for max_hiking_difficulty.",
      },
      {
        name: "mode_factor",
        type: "number",
        default: 1.5,
        minimum: 0.1,
        maximum: 100000,
        description:
          "A factor which the cost of a pedestrian edge will be multiplied with on multimodal request, e.g. `bss` or `multimodal/transit`. Default is a factor of 1.5, i.e. avoiding walking.",
      },
      {
        name: "max_distance",
        type: "integer",
        minimum: 0,
        description:
          "Sets the maximum total walking distance of a route in meters. Default 100000 (foot), 10000 (wheelchair).",
      },
      {
        name: "multimodal_start_end_max_distance",
        type: "integer",
        default: 2415,
        minimum: 0,
        description:
          "(**Note**: renamed from `transit_start_end_max_distance`) A pedestrian option that can be added to the request to extend the defaults (2145 meters or approximately 1.5 miles). This is the maximum walking distance at the beginning or end of a route.",
      },
      {
        name: "transit_transfer_max_distance",
        type: "integer",
        default: 805,
        minimum: 0,
        description:
          "A pedestrian option that can be added to the request to extend the defaults (800 meters or 0.5 miles). This is the maximum walking distance between transfers.",
      },
      {
        name: "use_hills",
        type: "number",
        default: 0.5,
        minimum: 0,
        maximum: 1,
        description:
          "This is a range of values from 0 to 1, where 0 attempts to avoid hills and steep grades even if it means a longer (time and distance) path, while 1 indicates the pedestrian does not fear hills and steeper grades. Based on the `use_hills` factor, penalties are applied to roads based on elevation change and grade. These penalties help the path avoid hilly roads in favor of flatter roads or less steep grades where available. Note that it is not always possible to find alternate paths to avoid hills (for example when route locations are in mountainous areas).",
      },
      {
        name: "elevator_penalty",
        type: "number",
        default: 5,
        minimum: 0,
        maximum: 43200,
        description:
          "A penalty in seconds added to each transition via an elevator node or onto an elevator edge. Higher values apply larger cost penalties to avoid elevators.",
      },
      {
        name: "bss_rent_cost",
        type: "number",
        default: 120,
        minimum: 0,
        maximum: 43200,
        description:
          "This value is useful when `bikeshare` is chosen as travel mode. It is meant to give the time will be used to rent a bike from a bike share station. This value will be displayed in the final directions and used to calculate the whole duration.",
      },
      {
        name: "bss_rent_penalty",
        type: "number",
        default: 0,
        minimum: 0,
        maximum: 43200,
        description:
          "This value is useful when `bikeshare` is chosen as travel mode. It is meant to describe the potential effort to rent a bike from a bike share station. This value won't be displayed and used only inside of the algorithm.",
      },
    ],
    Transit: [
      {
        name: "mode_factor",
        type: "number",
        default: 1.0,
        minimum: 0.1,
        maximum: 100000,
        description:
          "A factor which the cost of a transit edge will be multiplied with.",
      },
      {
        name: "wheelchair",
        type: "boolean",
        default: false,
        description: "Require wheelchair-accessible transit.",
      },
      {
        name: "bicycle",
        type: "boolean",
        default: false,
        description: "Allow bicycle on transit.",
      },
      {
        name: "use_bus",
        type: "number",
        default: 0.3,
        minimum: 0,
        maximum: 1,
        description:
          "User's desire to use buses. Range of values from 0 (try to avoid buses) to 1 (strong preference for riding buses).",
      },
      {
        name: "use_rail",
        type: "number",
        default: 0.6,
        minimum: 0,
        maximum: 1,
        description:
          "User's desire to use rail/subway/metro. Range of values from 0 (try to avoid rail) to 1 (strong preference for riding rail).",
      },
      {
        name: "use_transfers",
        type: "number",
        default: 0.3,
        minimum: 0,
        maximum: 1,
        description:
          "User's desire to favor transfers. Range of values from 0 (try to avoid transfers) to 1 (totally comfortable with transfers).",
      },
      {
        name: "transfer_cost",
        type: "number",
        default: 15,
        minimum: 0,
        maximum: 43200,
        description: "Time cost (seconds) per transfer. Influences ETA.",
      },
      {
        name: "transfer_penalty",
        type: "number",
        default: 300,
        minimum: 0,
        maximum: 43200,
        description:
          "Additional penalty (seconds) per transfer. Does not influence ETA.",
      },
    ],
    Truck: [
      {
        name: "hazmat",
        type: "boolean",
        default: false,
        description:
          "A value indicating if the truck is carrying hazardous materials.",
      },
      {
        name: "low_class_penalty",
        type: "number",
        default: 30,
        minimum: 0,
        maximum: 43200,
        description:
          "A penalty in seconds which is applied when transitioning down onto residential or service roads.",
      },
      {
        name: "low_class_factor",
        type: "number",
        default: 1.5,
        minimum: 0.1,
        maximum: 100000,
        description:
          "A factor which is applied to residential or service roads.",
      },
      {
        name: "height",
        type: "number",
        default: 4.11,
        description:
          "Vehicle height in meters for access restriction matching.",
      },
      {
        name: "width",
        type: "number",
        default: 2.6,
        description: "Vehicle width in meters for access restriction matching.",
      },
      {
        name: "length",
        type: "number",
        default: 21.64,
        description:
          "Vehicle length in meters for access restriction matching.",
      },
      {
        name: "weight",
        type: "number",
        default: 21.77,
        description:
          "Vehicle weight in metric tons for access restriction matching.",
      },
      {
        name: "axle_load",
        type: "number",
        default: 9.07,
        minimum: 0,
        maximum: 40,
        description:
          "Per-axle load in metric tons (default 20,000 lbs / ~9.07 t).",
      },
      {
        name: "axle_count",
        type: "integer",
        default: 5,
        minimum: 2,
        maximum: 20,
        description: "The axle count of the truck.",
      },
      {
        name: "use_highways",
        type: "number",
        default: 0.5,
        minimum: 0,
        maximum: 1,
        description:
          "This value indicates the willingness to take highways. This is a range of values between 0 and 1. Values near 0 attempt to avoid highways and values near 1 will favor highways. Note that sometimes highways are required to complete a route so values of 0 are not guaranteed to avoid highways entirely.",
      },
      {
        name: "use_tolls",
        type: "number",
        default: 0.5,
        minimum: 0,
        maximum: 1,
        description:
          "This value indicates the willingness to take roads with tolls. This is a range of values between 0 and 1. Values smaller than 0.5 attempt to avoid tolls and values greater than 0.5 will slightly favor them. The default value is 0.5, indicating no preference. Note that sometimes roads with tolls are required to complete a route so values of 0 are not guaranteed to avoid them entirely.",
      },
      {
        name: "top_speed",
        type: "number",
        default: 120,
        minimum: 10,
        maximum: 252,
        description:
          "Top speed the vehicle can go in km/h. Also used to avoid roads with higher speeds than this value. `top_speed` must be between 10 and 252 km/h. The default value is 120 km/h for truck.",
      },
      {
        name: "hgv_no_access_penalty",
        type: "number",
        default: 43200,
        minimum: 0,
        maximum: 43200,
        description:
          "A penalty applied to roads with no HGV/truck access. If set to a value less than 43200 seconds, HGV will be allowed on these roads and the penalty applies. Default 43200, i.e. trucks are not allowed.",
      },
      {
        name: "use_truck_route",
        type: "number",
        default: 0,
        minimum: 0,
        maximum: 1,
        description:
          "This value is a range of values from 0 to 1, where 0 indicates a light preference for streets marked as truck routes, and 1 indicates that streets not marked as truck routes should be avoided. This information is derived from the `hgv=designated` tag. Note that even with values near 1, there is no guarantee the returned route will include streets marked as truck routes.",
      },
      {
        name: "use_distance",
        type: "number",
        default: 0,
        minimum: 0,
        maximum: 1,
        description:
          "A factor that allows controlling the contribution of distance and time to the route costs. The value is in range between 0 and 1, where 0 only takes time into account and 1 only distance. A factor of 0.5 will weigh them roughly equally.",
      },
    ],
  },
};
