#!/usr/bin/env python3
"""Writes costing-options.js from the costing option schemas in Valhalla's OpenAPI spec.

Usage: ./generate-costing-options.py [path/to/valhalla/docs/docs/api/openapi.yaml]
"""
import json
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).parent
DEFAULT_SPEC = HERE / '../../valhalla/docs/docs/api/openapi.yaml'
SUFFIX = 'CostingOptions'
# `name` only matters for recostings
SKIPPED = {'name'}


def resolve(schemas, schema):
    """The properties of a schema, with its allOf parts and $refs merged in."""
    if '$ref' in schema:
        return resolve(schemas, schemas[schema['$ref'].rsplit('/', 1)[1]])
    properties = {}
    for part in schema.get('allOf', []):
        properties.update(resolve(schemas, part))
    properties.update(schema.get('properties', {}))
    return properties


def options(properties):
    result = []
    for name, spec in properties.items():
        # arrays and objects are left to the request JSON
        if name in SKIPPED or spec.get('type') not in ('number', 'integer', 'boolean', 'string'):
            continue
        option = {'name': name, 'type': spec['type']}
        for key in ('default', 'minimum', 'maximum', 'enum'):
            if key in spec:
                option[key] = spec[key]
        option['description'] = ' '.join(spec.get('description', '').split())
        result.append(option)
    return result


def main():
    spec_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SPEC
    schemas = yaml.safe_load(spec_path.read_text())['components']['schemas']

    base = resolve(schemas, schemas['Base' + SUFFIX])
    data = {
        'types': schemas['CostingType']['enum'],
        # which of the schemas below the options of a costing follow
        'costings': {costing: ref['$ref'].rsplit('/', 1)[1].removesuffix(SUFFIX) for costing, ref in schemas[SUFFIX]['properties'].items()},
        'schemas': {'Base': options(base)},
    }
    for name in sorted(set(data['costings'].values())):
        own = {key: value for key, value in resolve(schemas, schemas[name + SUFFIX]).items() if base.get(key) != value}
        data['schemas'][name] = options(own)

    text = json.dumps(data, indent=2, ensure_ascii=False)
    (HERE / 'costing-options.js').write_text(
        "// Generated by generate-costing-options.py from Valhalla's docs/docs/api/openapi.yaml, do not edit.\n"
        f'const COSTING_OPTIONS = {text};\n'
    )


if __name__ == '__main__':
    main()
